
// export const productsData=[
//   {
//     "id": 1,
//     "name": "Classic Cotton Crew Tee",
//     "category": "Men T-Shirt",
//     "brand": "UrbanWear",
//     "price": 499,
//     "discountPrice": 399,
//     "sizes": ["S", "M", "L", "XL"],
//     "colors": ["Black", "White"],
//     "material": "100% Cotton",
//     "fit": "Regular Fit",
//     "description": "Comfortable cotton t-shirt for daily wear.",
//     "images": ["https://images.unsplash.com/photo-1740711152088-88a009e877bb?q=80&w=880&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"]
//   },
//   {
//     "id": 2,
//     "name": "Slim Fit Solid Tee",
//     "category": "Men T-Shirt",
//     "brand": "StyleHub",
//     "price": 699,
//     "discountPrice": 549,
//     "sizes": ["M", "L", "XL"],
//     "colors": ["Navy", "Maroon"],
//     "material": "Cotton Blend",
//     "fit": "Slim Fit",
//     "description": "Modern slim fit t-shirt with soft finish.",
//     "images": ["https://plus.unsplash.com/premium_photo-1661627681947-4431c8c97659?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"]
//   },
//   {
//     "id": 3,
//     "name": "Graphic Street T-Shirt",
//     "category": "Men T-Shirt",
//     "brand": "StreetX",
//     "price": 799,
//     "discountPrice": 649,
//     "sizes": ["S", "M", "L"],
//     "colors": ["Black"],
//     "material": "Cotton",
//     "fit": "Oversized",
//     "description": "Street-style graphic t-shirt with bold print.",
//     "images": ["https://images.unsplash.com/photo-1635091984256-dc15291bb483?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"]
//   },
//   {
//     "id": 4,
//     "name": "Minimal Logo Tee",
//     "category": "Men T-Shirt",
//     "brand": "MonoFit",
//     "price": 599,
//     "discountPrice": 479,
//     "sizes": ["S", "M", "L", "XL"],
//     "colors": ["White", "Beige"],
//     "material": "Pure Cotton",
//     "fit": "Regular Fit",
//     "description": "Minimal logo t-shirt for clean styling.",
//     "images": ["https://plus.unsplash.com/premium_photo-1683140431958-31505d0fd1ff?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"]
//   },
//   {
//     "id": 5,
//     "name": "Dry Fit Sports T-Shirt",
//     "category": "Men T-Shirt",
//     "brand": "ActivePro",
//     "price": 899,
//     "discountPrice": 749,
//     "sizes": ["M", "L", "XL", "XXL"],
//     "colors": ["Blue", "Black"],
//     "material": "Polyester",
//     "fit": "Athletic Fit",
//     "description": "Quick-dry t-shirt perfect for workouts.",
//     "images": ["https://images.unsplash.com/photo-1635650805015-2fa50682873a?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"]
//   },
//   {
//     "id": 6,
//     "name": "Oversized Drop Shoulder Tee",
//     "category": "Men T-Shirt",
//     "brand": "HypeMode",
//     "price": 999,
//     "discountPrice": 799,
//     "sizes": ["M", "L", "XL"],
//     "colors": ["Brown", "Black"],
//     "material": "Heavy Cotton",
//     "fit": "Oversized",
//     "description": "Trendy oversized t-shirt with drop shoulders.",
//     "images": ["https://images.unsplash.com/photo-1618979507950-8b87ee54de19?q=80&w=686&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"]
//   },
//   {
//     "id": 7,
//     "name": "Striped Casual T-Shirt",
//     "category": "Men T-Shirt",
//     "brand": "StripeLab",
//     "price": 699,
//     "discountPrice": 569,
//     "sizes": ["M", "L", "XL"],
//     "colors": ["White-Blue"],
//     "material": "Cotton",
//     "fit": "Regular Fit",
//     "description": "Classic striped t-shirt for casual outings.",
//     "images": ["https://images.unsplash.com/photo-1516082669438-2d2bb5082626?q=80&w=1169&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"]
//   },
//   {
//     "id": 8,
//     "name": "Henley Neck T-Shirt",
//     "category": "Men T-Shirt",
//     "brand": "UrbanClassic",
//     "price": 749,
//     "discountPrice": 599,
//     "sizes": ["S", "M", "L", "XL"],
//     "colors": ["Olive", "Grey"],
//     "material": "Cotton Blend",
//     "fit": "Regular Fit",
//     "description": "Stylish henley neck t-shirt with button placket.",
//     "images": ["https://images.unsplash.com/photo-1627686011747-74adda3d2343?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"]
//   },
//   {
//     "id": 9,
//     "name": "Plain Round Neck Tee",
//     "category": "Men T-Shirt",
//     "brand": "DailyBasics",
//     "price": 399,
//     "discountPrice": 299,
//     "sizes": ["S", "M", "L", "XL"],
//     "colors": ["Black", "White"],
//     "material": "Cotton",
//     "fit": "Regular Fit",
//     "description": "Essential plain round neck t-shirt.",
//     "images": ["https://images.unsplash.com/photo-1641380848962-807139c82b92?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"]
//   },
//   {
//     "id": 10,
//     "name": "Premium Polo T-Shirt",
//     "category": "Men T-Shirt",
//     "brand": "EliteWear",
//     "price": 1099,
//     "discountPrice": 899,
//     "sizes": ["M", "L", "XL"],
//     "colors": ["Navy", "Green"],
//     "material": "Pique Cotton",
//     "fit": "Regular Fit",
//     "description": "Premium polo t-shirt for smart casual wear.",
//     "images": ["https://images.unsplash.com/photo-1732904467242-d52d6d929aa9?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"]
//   },

//   {
//     "id": 11,
//     "name": "Washed Cotton Tee",
//     "category": "Men T-Shirt",
//     "brand": "Rugged",
//     "price": 649,
//     "discountPrice": 519,
//     "sizes": ["M", "L", "XL"],
//     "colors": ["Grey"],
//     "material": "Washed Cotton",
//     "fit": "Regular Fit",
//     "description": "Vintage washed cotton t-shirt.",
//     "images": ["https://images.unsplash.com/photo-1646978124942-1314dd597473?q=80&w=673&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"]
//   },
//   {
//     "id": 12,
//     "name": "Printed Summer Tee",
//     "category": "Men T-Shirt",
//     "brand": "SunStyle",
//     "price": 549,
//     "discountPrice": 429,
//     "sizes": ["S", "M", "L"],
//     "colors": ["Yellow"],
//     "material": "Cotton",
//     "fit": "Slim Fit",
//     "description": "Lightweight summer t-shirt with print.",
//     "images": ["https://images.unsplash.com/photo-1586793810436-0851834fe086?q=80&w=626&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"]
//   },

//   {
//     "id": 13,
//     "name": "Longline T-Shirt",
//     "category": "Men T-Shirt",
//     "brand": "EdgeWear",
//     "price": 799,
//     "discountPrice": 649,
//     "sizes": ["M", "L", "XL"],
//     "colors": ["Black"],
//     "material": "Cotton Blend",
//     "fit": "Longline Fit",
//     "description": "Extended length longline t-shirt.",
//     "images": ["https://images.unsplash.com/photo-1648301558657-b55db298200a?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"]
//   },

//   {
//     "id": 14,
//     "name": "V-Neck Cotton Tee",
//     "category": "Men T-Shirt",
//     "brand": "SoftWear",
//     "price": 499,
//     "discountPrice": 379,
//     "sizes": ["S", "M", "L", "XL"],
//     "colors": ["White", "Blue"],
//     "material": "Cotton",
//     "fit": "Regular Fit",
//     "description": "Soft cotton v-neck t-shirt.",
//     "images": ["https://images.unsplash.com/photo-1684780932918-a66efb799c37?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"]
//   },

//   {
//     "id": 15,
//     "name": "Color Block T-Shirt",
//     "category": "Men T-Shirt",
//     "brand": "TrendLab",
//     "price": 849,
//     "discountPrice": 699,
//     "sizes": ["M", "L", "XL"],
//     "colors": ["Black-Red"],
//     "material": "Cotton",
//     "fit": "Regular Fit",
//     "description": "Trendy color block t-shirt.",
//     "images": ["https://images.unsplash.com/photo-1592660503155-7599a37f06a6?q=80&w=688&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"]
//   },
//   {
//     "id": 16,
//     "name": "Text Print Casual Tee",
//     "category": "Men T-Shirt",
//     "brand": "WordPlay",
//     "price": 599,
//     "discountPrice": 469,
//     "sizes": ["S", "M", "L"],
//     "colors": ["Black"],
//     "material": "Cotton",
//     "fit": "Regular Fit",
//     "description": "Casual t-shirt with trendy text print.",
//     "images": ["https://plus.unsplash.com/premium_photo-1672790905765-147467ee8cba?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"]
//   },
//   {
//     "id": 17,
//     "name": "Pocket Style T-Shirt",
//     "category": "Men T-Shirt",
//     "brand": "UrbanPocket",
//     "price": 549,
//     "discountPrice": 429,
//     "sizes": ["M", "L", "XL"],
//     "colors": ["Grey", "Navy"],
//     "material": "Cotton",
//     "fit": "Regular Fit",
//     "description": "Stylish t-shirt with front pocket detail.",
//     "images": ["https://images.unsplash.com/photo-1632734269047-e17fecaea067?q=80&w=708&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"]
//   },
//   {
//     "id": 18,
//     "name": "Acid Wash Oversized Tee",
//     "category": "Men T-Shirt",
//     "brand": "RawDenim",
//     "price": 999,
//     "discountPrice": 799,
//     "sizes": ["M", "L", "XL"],
//     "colors": ["Charcoal"],
//     "material": "Cotton",
//     "fit": "Oversized",
//     "description": "Acid washed oversized t-shirt for street look.",
//     "images": ["https://images.unsplash.com/photo-1616442690473-2ec0c452715c?q=80&w=1171&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"]
//   },
//   {
//     "id": 19,
//     "name": "Contrast Neck T-Shirt",
//     "category": "Men T-Shirt",
//     "brand": "BoldFit",
//     "price": 649,
//     "discountPrice": 519,
//     "sizes": ["S", "M", "L", "XL"],
//     "colors": ["White-Black"],
//     "material": "Cotton Blend",
//     "fit": "Slim Fit",
//     "description": "Stylish contrast neck t-shirt.",
//     "images": ["https://plus.unsplash.com/premium_photo-1727942418332-d71398a73db8?q=80&w=735&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"]
//   },
//   {
//     "id": 20,
//     "name": "Athleisure Training Tee",
//     "category": "Men T-Shirt",
//     "brand": "FlexCore",
//     "price": 899,
//     "discountPrice": 729,
//     "sizes": ["M", "L", "XL", "XXL"],
//     "colors": ["Black", "Blue"],
//     "material": "Polyester",
//     "fit": "Athletic Fit",
//     "description": "Athleisure t-shirt designed for performance.",
//     "images": ["https://images.unsplash.com/photo-1599475735868-a8924c458792?q=80&w=626&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"]
//   },
//   {
//     "id": 21,
//     "name": "Solid Pastel T-Shirt",
//     "category": "Men T-Shirt",
//     "brand": "PastelCo",
//     "price": 499,
//     "discountPrice": 389,
//     "sizes": ["S", "M", "L"],
//     "colors": ["Mint", "Lavender"],
//     "material": "Cotton",
//     "fit": "Regular Fit",
//     "description": "Soft pastel solid t-shirt for summer wear.",
//     "images": ["https://images.unsplash.com/photo-1612766958570-dc22697d2b8e?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"]
//   },
//   {
//     "id": 22,
//     "name": "Typography Print Tee",
//     "category": "Men T-Shirt",
//     "brand": "InkMode",
//     "price": 699,
//     "discountPrice": 559,
//     "sizes": ["M", "L", "XL"],
//     "colors": ["Black", "White"],
//     "material": "Cotton",
//     "fit": "Regular Fit",
//     "description": "Typography printed t-shirt with modern design.",
//     "images": ["https://images.unsplash.com/photo-1612766959025-ac18e2b3bb96?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"]
//   },
//   {
//     "id": 23,
//     "name": "Melange Cotton T-Shirt",
//     "category": "Men T-Shirt",
//     "brand": "GreyScale",
//     "price": 649,
//     "discountPrice": 519,
//     "sizes": ["S", "M", "L", "XL"],
//     "colors": ["Light Grey"],
//     "material": "Melange Cotton",
//     "fit": "Regular Fit",
//     "description": "Melange fabric t-shirt with textured finish.",
//     "images": ["https://images.unsplash.com/photo-1516258454449-64fed1caa732?q=80&w=1171&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"]
//   },
//   {
//     "id": 24,
//     "name": "Raglan Sleeve T-Shirt",
//     "category": "Men T-Shirt",
//     "brand": "SportEdge",
//     "price": 749,
//     "discountPrice": 599,
//     "sizes": ["M", "L", "XL"],
//     "colors": ["White-Blue"],
//     "material": "Cotton Blend",
//     "fit": "Regular Fit",
//     "description": "Raglan sleeve t-shirt with sporty look.",
//     "images": ["https://images.unsplash.com/photo-1707414038523-b5d1c8294786?q=80&w=764&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"]
//   },
//   {
//     "id": 25,
//     "name": "Premium Supima Cotton Tee",
//     "category": "Men T-Shirt",
//     "brand": "LuxCotton",
//     "price": 1199,
//     "discountPrice": 999,
//     "sizes": ["M", "L", "XL"],
//     "colors": ["Black", "White"],
//     "material": "Supima Cotton",
//     "fit": "Regular Fit",
//     "description": "Ultra-soft premium Supima cotton t-shirt.",
//     "images": ["https://images.unsplash.com/photo-1757588379146-f75c41168da1?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"]
//   },
//   {
//     "id": 26,
//     "name": "Sleeveless Gym T-Shirt",
//     "category": "Men T-Shirt",
//     "brand": "IronFit",
//     "price": 499,
//     "discountPrice": 399,
//     "sizes": ["M", "L", "XL"],
//     "colors": ["Black", "Red"],
//     "material": "Cotton Blend",
//     "fit": "Athletic Fit",
//     "description": "Sleeveless t-shirt for intense workouts.",
//     "images": ["https://images.unsplash.com/photo-1582752722441-011c714a5ba6?q=80&w=715&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"]
//   },
//   {
//     "id": 27,
//     "name": "All Over Print Tee",
//     "category": "Men T-Shirt",
//     "brand": "Printify",
//     "price": 799,
//     "discountPrice": 649,
//     "sizes": ["S", "M", "L"],
//     "colors": ["Multicolor"],
//     "material": "Cotton",
//     "fit": "Regular Fit",
//     "description": "All-over printed t-shirt with bold patterns.",
//     "images": ["https://images.unsplash.com/photo-1616443154100-f2064e9f6ca7?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"]
//   },
//   {
//     "id": 28,
//     "name": "High Neck T-Shirt",
//     "category": "Men T-Shirt",
//     "brand": "NeoStyle",
//     "price": 749,
//     "discountPrice": 599,
//     "sizes": ["M", "L", "XL"],
//     "colors": ["Black"],
//     "material": "Cotton Blend",
//     "fit": "Slim Fit",
//     "description": "High neck t-shirt for a modern silhouette.",
//     "images": ["https://plus.unsplash.com/premium_photo-1727942411342-b16f0d576bfd?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"]
//   },
//   {
//     "id": 29,
//     "name": "Loose Fit Casual Tee",
//     "category": "Men T-Shirt",
//     "brand": "FreeMove",
//     "price": 599,
//     "discountPrice": 469,
//     "sizes": ["L", "XL", "XXL"],
//     "colors": ["Olive"],
//     "material": "Cotton",
//     "fit": "Loose Fit",
//     "description": "Relaxed fit t-shirt for comfort wear.",
//     "images": ["https://images.unsplash.com/photo-1615851947829-3641ababa187?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"]
//   },
//   {
//     "id": 30,
//     "name": "Organic Cotton T-Shirt",
//     "category": "Men T-Shirt",
//     "brand": "EcoWear",
//     "price": 899,
//     "discountPrice": 749,
//     "sizes": ["S", "M", "L", "XL"],
//     "colors": ["Natural White"],
//     "material": "Organic Cotton",
//     "fit": "Regular Fit",
//     "description": "Eco-friendly organic cotton t-shirt.",
//     "images": ["https://images.unsplash.com/photo-1765175094470-ed3bef04ed40?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"]
//   },
//   {
//     "id": 31,
//     "name": "Crew Neck Everyday Tee",
//     "category": "Men T-Shirt",
//     "brand": "Everyday",
//     "price": 449,
//     "discountPrice": 349,
//     "sizes": ["S", "M", "L", "XL"],
//     "colors": ["Black", "Grey"],
//     "material": "Cotton",
//     "fit": "Regular Fit",
//     "description": "Simple everyday crew neck t-shirt.",
//     "images": ["https://images.unsplash.com/photo-1602810316693-3667c854239a?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"]
//   },
//   {
//     "id": 32,
//     "name": "Camouflage Print Tee",
//     "category": "Men T-Shirt",
//     "brand": "Militant",
//     "price": 799,
//     "discountPrice": 649,
//     "sizes": ["M", "L", "XL"],
//     "colors": ["Camo Green"],
//     "material": "Cotton",
//     "fit": "Regular Fit",
//     "description": "Camouflage printed t-shirt for rugged style.",
//     "images": ["https://plus.unsplash.com/premium_photo-1720424468006-337f80b31c6c?q=80&w=1074&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"]
//   },
//   {
//     "id": 33,
//     "name": "Neon Accent T-Shirt",
//     "category": "Men T-Shirt",
//     "brand": "Flash",
//     "price": 699,
//     "discountPrice": 559,
//     "sizes": ["M", "L"],
//     "colors": ["Black-Neon"],
//     "material": "Cotton Blend",
//     "fit": "Slim Fit",
//     "description": "T-shirt with neon accent details.",
//     "images": ["https://images.unsplash.com/photo-1586430921696-c00f6dd64f89?q=80&w=776&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"]
//   },
//   {
//     "id": 34,
//     "name": "Round Hem Long Tee",
//     "category": "Men T-Shirt",
//     "brand": "CurveFit",
//     "price": 749,
//     "discountPrice": 599,
//     "sizes": ["M", "L", "XL"],
//     "colors": ["Black"],
//     "material": "Cotton",
//     "fit": "Longline Fit",
//     "description": "Long t-shirt with rounded hem.",
//     "images": ["https://plus.unsplash.com/premium_photo-1687279092829-3ba97563a12e?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"]
//   },
//   {
//     "id": 35,
//     "name": "Dual Tone Casual Tee",
//     "category": "Men T-Shirt",
//     "brand": "ToneUp",
//     "price": 699,
//     "discountPrice": 569,
//     "sizes": ["M", "L", "XL"],
//     "colors": ["Blue-Grey"],
//     "material": "Cotton",
//     "fit": "Regular Fit",
//     "description": "Dual tone t-shirt with modern appeal.",
//     "images": ["https://images.unsplash.com/photo-1653694053345-b22f94c95bcf?q=80&w=622&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"]
//   },
//   {
//     "id": 36,
//     "name": "Reflective Print T-Shirt",
//     "category": "Men T-Shirt",
//     "brand": "NightRun",
//     "price": 899,
//     "discountPrice": 749,
//     "sizes": ["M", "L", "XL"],
//     "colors": ["Black"],
//     "material": "Polyester Blend",
//     "fit": "Athletic Fit",
//     "description": "Reflective print t-shirt for night workouts.",
//     "images": ["https://images.unsplash.com/photo-1763610452272-eef78d1d62c4?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"]
//   },
//   {
//     "id": 37,
//     "name": "Basic Solid Cotton Tee",
//     "category": "Men T-Shirt",
//     "brand": "CottonClub",
//     "price": 399,
//     "discountPrice": 299,
//     "sizes": ["S", "M", "L", "XL"],
//     "colors": ["White", "Black"],
//     "material": "Cotton",
//     "fit": "Regular Fit",
//     "description": "Basic solid cotton t-shirt.",
//     "images": ["https://images.unsplash.com/photo-1589234217365-08d3e0e5cf42?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"]
//   },
//   {
//     "id": 38,
//     "name": "Relaxed Weekend T-Shirt",
//     "category": "Men T-Shirt",
//     "brand": "Weekend",
//     "price": 549,
//     "discountPrice": 429,
//     "sizes": ["M", "L", "XL"],
//     "colors": ["Sky Blue"],
//     "material": "Cotton",
//     "fit": "Relaxed Fit",
//     "description": "Relaxed fit t-shirt for weekends.",
//     "images": ["https://images.unsplash.com/photo-1639747277258-28312ae9505b?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"]
//   },
//   {
//     "id": 39,
//     "name": "Bold Logo Statement Tee",
//     "category": "Men T-Shirt",
//     "brand": "LogoMan",
//     "price": 799,
//     "discountPrice": 649,
//     "sizes": ["M", "L"],
//     "colors": ["Black"],
//     "material": "Cotton",
//     "fit": "Oversized",
//     "description": "Bold logo t-shirt for statement looks.",
//     "images": ["https://images.unsplash.com/photo-1732061906977-cbc5cdded265?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"]
//   },
//   {
//     "id": 40,
//     "name": "Soft Touch Modal Tee",
//     "category": "Men T-Shirt",
//     "brand": "SoftLux",
//     "price": 899,
//     "discountPrice": 749,
//     "sizes": ["M", "L", "XL"],
//     "colors": ["Beige"],
//     "material": "Modal Blend",
//     "fit": "Regular Fit",
//     "description": "Ultra-soft modal blend t-shirt.",
//     "images": ["https://plus.unsplash.com/premium_photo-1727967291564-aa94bd08cf46?q=80&w=735&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"]
//   },
//   {
//     "id": 41,
//     "name": "Urban Fit Casual Tee",
//     "category": "Men T-Shirt",
//     "brand": "CityWear",
//     "price": 649,
//     "discountPrice": 519,
//     "sizes": ["M", "L", "XL"],
//     "colors": ["Black"],
//     "material": "Cotton",
//     "fit": "Slim Fit",
//     "description": "Urban style slim fit t-shirt.",
//     "images": ["https://plus.unsplash.com/premium_photo-1727967194388-d838e1f37dec?q=80&w=735&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"]
//   },
//   {
//     "id": 42,
//     "name": "Side Stripe T-Shirt",
//     "category": "Men T-Shirt",
//     "brand": "TrackLine",
//     "price": 749,
//     "discountPrice": 599,
//     "sizes": ["M", "L", "XL"],
//     "colors": ["Black-White"],
//     "material": "Cotton Blend",
//     "fit": "Regular Fit",
//     "description": "Side stripe t-shirt with sporty feel.",
//     "images": ["https://images.unsplash.com/photo-1619011940610-eda7c2ab3477?q=80&w=686&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"]
//   },
//   {
//     "id": 43,
//     "name": "Vintage Wash Cotton Tee",
//     "category": "Men T-Shirt",
//     "brand": "RetroFit",
//     "price": 849,
//     "discountPrice": 699,
//     "sizes": ["M", "L"],
//     "colors": ["Faded Blue"],
//     "material": "Washed Cotton",
//     "fit": "Regular Fit",
//     "description": "Vintage wash t-shirt with retro vibe.",
//     "images": ["https://images.unsplash.com/photo-1761126085595-c9b8a83912cd?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"]
//   },
//   {
//     "id": 44,
//     "name": "Stretch Fit Performance Tee",
//     "category": "Men T-Shirt",
//     "brand": "MoveX",
//     "price": 899,
//     "discountPrice": 749,
//     "sizes": ["M", "L", "XL"],
//     "colors": ["Black"],
//     "material": "Poly Stretch",
//     "fit": "Athletic Fit",
//     "description": "Stretch performance t-shirt for active use.",
//     "images": ["https://images.unsplash.com/photo-1741601466156-82ff4dcc4225?q=80&w=1150&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"]
//   },
//   {
//     "id": 45,
//     "name": "Dual Pocket Casual Tee",
//     "category": "Men T-Shirt",
//     "brand": "Utility",
//     "price": 699,
//     "discountPrice": 559,
//     "sizes": ["M", "L", "XL"],
//     "colors": ["Olive"],
//     "material": "Cotton",
//     "fit": "Regular Fit",
//     "description": "Utility-inspired dual pocket t-shirt.",
//     "images": ["https://images.unsplash.com/photo-1761726080374-fb14053b2f0e?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"]
//   },
//   {
//     "id": 46,
//     "name": "All Black Essential Tee",
//     "category": "Men T-Shirt",
//     "brand": "DarkMode",
//     "price": 499,
//     "discountPrice": 399,
//     "sizes": ["S", "M", "L", "XL"],
//     "colors": ["Black"],
//     "material": "Cotton",
//     "fit": "Regular Fit",
//     "description": "All black essential t-shirt.",
//     "images": ["https://images.unsplash.com/photo-1628274794542-d1c3700f03d8?q=80&w=1173&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"]
//   },
//   {
//     "id": 47,
//     "name": "Color Fade T-Shirt",
//     "category": "Men T-Shirt",
//     "brand": "FadeOut",
//     "price": 799,
//     "discountPrice": 649,
//     "sizes": ["M", "L"],
//     "colors": ["Blue Fade"],
//     "material": "Cotton",
//     "fit": "Regular Fit",
//     "description": "Color faded t-shirt with unique finish.",
//     "images": ["https://images.unsplash.com/photo-1693287728941-2e0125a67f90?q=80&w=880&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"]
//   },
//   {
//     "id": 48,
//     "name": "Panel Design Casual Tee",
//     "category": "Men T-Shirt",
//     "brand": "PanelX",
//     "price": 749,
//     "discountPrice": 599,
//     "sizes": ["M", "L", "XL"],
//     "colors": ["Grey-Black"],
//     "material": "Cotton Blend",
//     "fit": "Regular Fit",
//     "description": "Panel design t-shirt with modern look.",
//     "images": ["https://plus.unsplash.com/premium_photo-1664303979167-e2aaad5628a5?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"]
//   },
//   {
//     "id": 49,
//     "name": "Premium Everyday Tee",
//     "category": "Men T-Shirt",
//     "brand": "PrimeWear",
//     "price": 999,
//     "discountPrice": 849,
//     "sizes": ["M", "L", "XL"],
//     "colors": ["White"],
//     "material": "Premium Cotton",
//     "fit": "Regular Fit",
//     "description": "Premium everyday t-shirt with soft touch.",
//     "images": ["https://images.unsplash.com/photo-1627389891394-09f8457c481e?q=80&w=765&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"]
//   },
//   {
//     "id": 50,
//     "name": "Comfort Lounge T-Shirt",
//     "category": "Men T-Shirt",
//     "brand": "HomeEase",
//     "price": 549,
//     "discountPrice": 429,
//     "sizes": ["L", "XL", "XXL"],
//     "colors": ["Heather Grey"],
//     "material": "Cotton Blend",
//     "fit": "Relaxed Fit",
//     "description": "Comfortable lounge t-shirt for home wear.",
//     "images": ["https://images.unsplash.com/photo-1732061905717-9cdbc300c8ac?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"]
//   }



 
// ]


export const productsData = 
[
  
  {
    "id": 1,
    "name": "Classic Cotton Women's Tee",
    "category": "Women Tops",
    "brand": "UrbanShe",
    "price": 499,
    "discountPrice": 399,
    "sizes": ["S", "M", "L", "XL"],
    "colors": ["White", "Black"],
    "material": "Cotton",
    "fit": "Regular Fit",
    "description": "Soft cotton t-shirt for everyday comfort.",
    "images": ["https://plus.unsplash.com/premium_photo-1687188210526-50610de047d8?q=80&w=988&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"]
  },
  {
    "id": 2,
    "name": "Slim Fit Ribbed Top",
    "category": "Women Tops",
    "brand": "StyleAura",
    "price": 699,
    "discountPrice": 549,
    "sizes": ["S", "M", "L"],
    "colors": ["Beige", "Brown"],
    "material": "Ribbed Cotton",
    "fit": "Slim Fit",
    "description": "Ribbed slim-fit top with stretch fabric.",
    "images": ["https://plus.unsplash.com/premium_photo-1698749344903-2639d1cc31a1?q=80&w=987&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"]
  },
  {
    "id": 3,
    "name": "Oversized Street Tee",
    "category": "Women Tops",
    "brand": "StreetMuse",
    "price": 899,
    "discountPrice": 699,
    "sizes": ["M", "L", "XL"],
    "colors": ["Grey"],
    "material": "Cotton",
    "fit": "Oversized",
    "description": "Trendy oversized t-shirt for street wear.",
    "images": ["https://images.unsplash.com/photo-1764337593393-04dca99acd2f?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"]
  },
  {
    "id": 4,
    "name": "Printed Summer Top",
    "category": "Women Tops",
    "brand": "SunLush",
    "price": 599,
    "discountPrice": 449,
    "sizes": ["S", "M", "L"],
    "colors": ["Yellow"],
    "material": "Cotton",
    "fit": "Regular Fit",
    "description": "Bright printed top for summer days.",
    "images": ["https://images.unsplash.com/photo-1765529374855-7353c3c47fc6?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"]
  },
  {
    "id": 5,
    "name": "Crop Fit Casual Tee",
    "category": "Women Tops",
    "brand": "HypeHer",
    "price": 549,
    "discountPrice": 429,
    "sizes": ["S", "M", "L"],
    "colors": ["Pink"],
    "material": "Cotton Blend",
    "fit": "Crop Fit",
    "description": "Stylish crop t-shirt for casual outings.",
    "images": ["https://images.unsplash.com/photo-1530981785497-a62037228fe9?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"]
  },

  {
    "id": 6,
    "name": "V-Neck Everyday Tee",
    "category": "Women Tops",
    "brand": "SoftLine",
    "price": 499,
    "discountPrice": 379,
    "sizes": ["S", "M", "L", "XL"],
    "colors": ["White"],
    "material": "Cotton",
    "fit": "Regular Fit",
    "description": "Comfortable v-neck tee for daily wear.",
    "images": ["https://plus.unsplash.com/premium_photo-1675186049366-64a655f8f537?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"]
  },
  {
    "id": 7,
    "name": "Longline Relaxed Top",
    "category": "Women Tops",
    "brand": "EaseWear",
    "price": 799,
    "discountPrice": 649,
    "sizes": ["M", "L", "XL"],
    "colors": ["Black"],
    "material": "Cotton",
    "fit": "Relaxed Fit",
    "description": "Longline top with relaxed silhouette.",
    "images": ["https://images.unsplash.com/photo-1616313253719-c46514cddee1?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"]
  },
  {
    "id": 8,
    "name": "Henley Neck Women's Tee",
    "category": "Women Tops",
    "brand": "UrbanCharm",
    "price": 749,
    "discountPrice": 599,
    "sizes": ["S", "M", "L"],
    "colors": ["Olive"],
    "material": "Cotton Blend",
    "fit": "Regular Fit",
    "description": "Henley neck top with button detailing.",
    "images": ["https://images.unsplash.com/photo-1434389677669-e08b4cac3105?q=80&w=705&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"]
  },

  {
    "id": 9,
    "name": "Striped Casual Tee",
    "category": "Women Tops",
    "brand": "StripeSoul",
    "price": 699,
    "discountPrice": 549,
    "sizes": ["M", "L"],
    "colors": ["White-Blue"],
    "material": "Cotton",
    "fit": "Regular Fit",
    "description": "Classic striped casual t-shirt.",
    "images": ["https://images.unsplash.com/photo-1525845859779-54d477ff291f?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"]
  },
  {
    "id": 10,
    "name": "Athleisure Dry Fit Top",
    "category": "Women Tops",
    "brand": "ActiveQueen",
    "price": 999,
    "discountPrice": 799,
    "sizes": ["S", "M", "L", "XL"],
    "colors": ["Black"],
    "material": "Polyester",
    "fit": "Athletic Fit",
    "description": "Quick dry activewear top for workouts.",
    "images": ["https://images.unsplash.com/photo-1558769132-cb1aea458c5e?q=80&w=1074&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"]
  },
  {
    "id": 11,
    "name": "Soft Knit Casual Top",
    "category": "Women Tops",
    "brand": "CozyWear",
    "price": 799,
    "discountPrice": 649,
    "sizes": ["S", "M", "L"],
    "colors": ["Cream"],
    "material": "Knit Cotton",
    "fit": "Regular Fit",
    "description": "Soft knit top perfect for relaxed days.",
    "images": ["https://images.unsplash.com/photo-1532453288672-3a27e9be9efd?q=80&w=764&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"]
  },
  {
    "id": 12,
    "name": "Relaxed Fit Lounge Tee",
    "category": "Women Tops",
    "brand": "EaseMode",
    "price": 599,
    "discountPrice": 479,
    "sizes": ["M", "L", "XL"],
    "colors": ["Grey"],
    "material": "Cotton Blend",
    "fit": "Relaxed Fit",
    "description": "Comfortable lounge t-shirt for home wear.",
    "images": ["https://images.unsplash.com/photo-1651743679361-201259835e44?q=80&w=764&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"]
  },
  {
    "id": 13,
    "name": "Boat Neck Solid Top",
    "category": "Women Tops",
    "brand": "PureLine",
    "price": 699,
    "discountPrice": 559,
    "sizes": ["S", "M", "L"],
    "colors": ["Navy"],
    "material": "Cotton",
    "fit": "Regular Fit",
    "description": "Elegant boat neck top with solid color.",
    "images": ["https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?q=80&w=720&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"]
  },
  {
    "id": 14,
    "name": "Ruffle Sleeve Top",
    "category": "Women Tops",
    "brand": "FemmeFit",
    "price": 899,
    "discountPrice": 749,
    "sizes": ["S", "M", "L"],
    "colors": ["Peach"],
    "material": "Cotton",
    "fit": "Regular Fit",
    "description": "Feminine ruffle sleeve casual top.",
    "images": ["https://images.unsplash.com/photo-1652473291442-7a2e034a00d1?q=80&w=764&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"]
  },
  {
    "id": 15,
    "name": "High Neck Ribbed Top",
    "category": "Women Tops",
    "brand": "UrbanCurve",
    "price": 749,
    "discountPrice": 599,
    "sizes": ["S", "M", "L"],
    "colors": ["Black"],
    "material": "Ribbed Cotton",
    "fit": "Slim Fit",
    "description": "High neck ribbed top for modern look.",
    "images": ["https://images.unsplash.com/photo-1582738509941-360b28c941ea?q=80&w=685&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"]
  },

  {
    "id": 16,
    "name": "Loose Fit Graphic Tee",
    "category": "Women Tops",
    "brand": "TrendMuse",
    "price": 849,
    "discountPrice": 699,
    "sizes": ["M", "L"],
    "colors": ["White"],
    "material": "Cotton",
    "fit": "Loose Fit",
    "description": "Graphic tee with relaxed fit.",
    "images": ["https://images.unsplash.com/photo-1651828855248-343042ecc906?q=80&w=764&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"]
  },
  {
    "id": 17,
    "name": "Tie-Up Waist Top",
    "category": "Women Tops",
    "brand": "ChicAura",
    "price": 999,
    "discountPrice": 829,
    "sizes": ["S", "M", "L"],
    "colors": ["Lavender"],
    "material": "Cotton Blend",
    "fit": "Regular Fit",
    "description": "Stylish tie-up waist casual top.",
    "images": ["https://images.unsplash.com/photo-1651828854976-4fa163b636ff?q=80&w=764&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"]
  },
  {
    "id": 18,
    "name": "Basic Everyday Tee",
    "category": "Women Tops",
    "brand": "DailyEase",
    "price": 399,
    "discountPrice": 299,
    "sizes": ["S", "M", "L", "XL"],
    "colors": ["White"],
    "material": "Cotton",
    "fit": "Regular Fit",
    "description": "Essential everyday basic t-shirt.",
    "images": ["https://images.unsplash.com/photo-1735553816746-229df9b3bd37?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"]
  },
  {
    "id": 19,
    "name": "Drop Shoulder Casual Tee",
    "category": "Women Tops",
    "brand": "StreetEase",
    "price": 899,
    "discountPrice": 729,
    "sizes": ["M", "L", "XL"],
    "colors": ["Brown"],
    "material": "Heavy Cotton",
    "fit": "Oversized",
    "description": "Drop shoulder tee with street vibe.",
    "images": ["https://images.unsplash.com/photo-1733395700989-febbc2d31ed8?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"]
  },
  {
    "id": 20,
    "name": "Soft Modal Blend Top",
    "category": "Women Tops",
    "brand": "SilkSoft",
    "price": 1099,
    "discountPrice": 899,
    "sizes": ["S", "M", "L"],
    "colors": ["Mint"],
    "material": "Modal Blend",
    "fit": "Regular Fit",
    "description": "Ultra-soft modal blend top.",
    "images": ["https://images.unsplash.com/photo-1739773375291-40f604de9468?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"]
  },

  {
    "id": 21,
    "name": "Minimal Printed Tee",
    "category": "Women Tops",
    "brand": "MonoMuse",
    "price": 699,
    "discountPrice": 549,
    "sizes": ["S", "M", "L"],
    "colors": ["Ivory"],
    "material": "Cotton",
    "fit": "Regular Fit",
    "description": "Minimal print casual t-shirt.",
    "images": ["https://images.unsplash.com/photo-1739773375403-36a4ba177f73?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"]
  },
  {
    "id": 22,
    "name": "Relaxed Scoop Neck Top",
    "category": "Women Tops",
    "brand": "SoftAura",
    "price": 649,
    "discountPrice": 519,
    "sizes": ["M", "L", "XL"],
    "colors": ["Blue"],
    "material": "Cotton",
    "fit": "Relaxed Fit",
    "description": "Scoop neck top with relaxed feel.",
    "images": ["https://images.unsplash.com/photo-1735553817411-78c7fb5e78c2?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"]
  },

  {
    "id": 23,
    "name": "Everyday Comfort Tee",
    "category": "Women Tops",
    "brand": "ComfyCo",
    "price": 499,
    "discountPrice": 389,
    "sizes": ["S", "M", "L", "XL"],
    "colors": ["Grey"],
    "material": "Cotton",
    "fit": "Regular Fit",
    "description": "Comfort-focused everyday t-shirt.",
    "images": ["https://plus.unsplash.com/premium_photo-1673757110542-e2ce512bf60e?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"]
  },

  {
    "id": 24,
    "name": "Urban Boxy Tee",
    "category": "Women Tops",
    "brand": "BoxMode",
    "price": 899,
    "discountPrice": 739,
    "sizes": ["M", "L"],
    "colors": ["Black"],
    "material": "Cotton",
    "fit": "Boxy Fit",
    "description": "Urban style boxy t-shirt.",
    "images": ["https://images.unsplash.com/photo-1735553816849-fed0daf9bf48?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"]
  },

  {
    "id": 25,
    "name": "Puff Sleeve Cotton Top",
    "category": "Women Tops",
    "brand": "GraceWear",
    "price": 999,
    "discountPrice": 829,
    "sizes": ["S", "M", "L"],
    "colors": ["White"],
    "material": "Cotton",
    "fit": "Regular Fit",
    "description": "Puff sleeve top with elegant style.",
    "images": ["https://images.unsplash.com/photo-1735553816887-95a2657d5fd8?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"]
  },

  {
    "id": 26,
    "name": "Casual Weekend Tee",
    "category": "Women Tops",
    "brand": "WeekendWear",
    "price": 549,
    "discountPrice": 429,
    "sizes": ["M", "L", "XL"],
    "colors": ["Olive"],
    "material": "Cotton",
    "fit": "Regular Fit",
    "description": "Perfect tee for weekend comfort.",
    "images": ["https://images.unsplash.com/photo-1735553817415-34af90cf7645?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"]
  },

  {
    "id": 27,
    "name": "Soft Stretch Fitted Top",
    "category": "Women Tops",
    "brand": "FlexFit",
    "price": 799,
    "discountPrice": 649,
    "sizes": ["S", "M", "L"],
    "colors": ["Black"],
    "material": "Cotton Elastane",
    "fit": "Fitted",
    "description": "Stretchable fitted top with comfort.",
    "images": ["https://images.unsplash.com/photo-1734944688796-a5ea7de7cfcc?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"]
  },

  {
    "id": 28,
    "name": "Casual Printed Top",
    "category": "Women Tops",
    "brand": "PrintLab",
    "price": 699,
    "discountPrice": 559,
    "sizes": ["S", "M", "L"],
    "colors": ["Pink"],
    "material": "Cotton",
    "fit": "Regular Fit",
    "description": "Printed top for daily casual wear.",
    "images": ["https://plus.unsplash.com/premium_photo-1675253527708-f07bf2f0d638?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"]
  },

  {
    "id": 29,
    "name": "Classic Everyday Tee",
    "category": "Women Tops",
    "brand": "Essentials",
    "price": 449,
    "discountPrice": 349,
    "sizes": ["S", "M", "L", "XL"],
    "colors": ["White"],
    "material": "Cotton",
    "fit": "Regular Fit",
    "description": "Classic everyday cotton tee.",
    "images": ["https://images.unsplash.com/photo-1733310925430-667f8ece82ee?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"]
  },

  {
    "id": 30,
    "name": "Modern Box Tee",
    "category": "Women Tops",
    "brand": "NeoWear",
    "price": 899,
    "discountPrice": 729,
    "sizes": ["M", "L"],
    "colors": ["Grey"],
    "material": "Cotton",
    "fit": "Box Fit",
    "description": "Modern box fit t-shirt.",
    "images": ["https://images.unsplash.com/photo-1733310925490-1011872200d8?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"]
  },

  {
    "id": 31,
    "name": "Everyday Relax Tee",
    "category": "Women Tops",
    "brand": "DailyMood",
    "price": 499,
    "discountPrice": 379,
    "sizes": ["S", "M", "L"],
    "colors": ["Blue"],
    "material": "Cotton",
    "fit": "Relaxed Fit",
    "description": "Relaxed t-shirt for everyday wear.",
    "images": ["https://images.unsplash.com/photo-1733311156460-bb9cce46b106?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"]
  },

  {
    "id": 32,
    "name": "Soft Lounge Cotton Top",
    "category": "Women Tops",
    "brand": "LoungeLux",
    "price": 649,
    "discountPrice": 519,
    "sizes": ["M", "L", "XL"],
    "colors": ["Beige"],
    "material": "Cotton",
    "fit": "Relaxed Fit",
    "description": "Soft cotton lounge top.",
    "images": ["https://images.unsplash.com/photo-1733395700641-216f17365506?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"]
  },

  {
    "id": 33,
    "name": "Casual Chic Tee",
    "category": "Women Tops",
    "brand": "ChicFit",
    "price": 799,
    "discountPrice": 639,
    "sizes": ["S", "M", "L"],
    "colors": ["White"],
    "material": "Cotton",
    "fit": "Regular Fit",
    "description": "Chic casual t-shirt for outings.",
    "images": ["https://plus.unsplash.com/premium_photo-1727943074995-48cf98247b5a?q=80&w=735&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"]
  },

  {
    "id": 34,
    "name": "Urban Comfort Top",
    "category": "Women Tops",
    "brand": "CityEase",
    "price": 699,
    "discountPrice": 549,
    "sizes": ["M", "L"],
    "colors": ["Black"],
    "material": "Cotton",
    "fit": "Regular Fit",
    "description": "Urban-inspired comfortable top.",
    "images": ["https://images.unsplash.com/photo-1733310925469-efcb541c7a16?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"]
  },

  {
    "id": 35,
    "name": "Premium Cotton Tee",
    "category": "Women Tops",
    "brand": "PureLux",
    "price": 1099,
    "discountPrice": 899,
    "sizes": ["S", "M", "L"],
    "colors": ["White"],
    "material": "Premium Cotton",
    "fit": "Regular Fit",
    "description": "Premium quality cotton t-shirt.",
    "images": ["https://images.unsplash.com/photo-1768289222368-62cbdfe7d5f5?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"]
  },

  {
    "id": 36,
    "name": "Relaxed Fit Solid Top",
    "category": "Women Tops",
    "brand": "CalmWear",
    "price": 599,
    "discountPrice": 469,
    "sizes": ["M", "L", "XL"],
    "colors": ["Olive"],
    "material": "Cotton",
    "fit": "Relaxed Fit",
    "description": "Relaxed solid color top.",
    "images": ["https://images.unsplash.com/photo-1652473291473-440ca687f82e?q=80&w=765&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"]
  },

  {
    "id": 37,
    "name": "Casual Street Tee",
    "category": "Women Tops",
    "brand": "StreetEase",
    "price": 849,
    "discountPrice": 699,
    "sizes": ["M", "L"],
    "colors": ["Grey"],
    "material": "Cotton",
    "fit": "Oversized",
    "description": "Street-style oversized tee.",
    "images": ["https://images.unsplash.com/photo-1652473291484-8b452af6e49c?q=80&w=764&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"]
  },

  {
    "id": 38,
    "name": "Everyday Cotton Top",
    "category": "Women Tops",
    "brand": "CottonWay",
    "price": 499,
    "discountPrice": 389,
    "sizes": ["S", "M", "L", "XL"],
    "colors": ["White"],
    "material": "Cotton",
    "fit": "Regular Fit",
    "description": "Everyday cotton essential top.",
    "images": ["https://images.unsplash.com/photo-1521510895919-46920266ddb3?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"]
  },

  {
    "id": 39,
    "name": "Lightweight Summer Tee",
    "category": "Women Tops",
    "brand": "SunEase",
    "price": 549,
    "discountPrice": 429,
    "sizes": ["S", "M", "L"],
    "colors": ["Yellow"],
    "material": "Light Cotton",
    "fit": "Regular Fit",
    "description": "Lightweight tee for summer wear.",
    "images": ["https://images.unsplash.com/photo-1612636676503-77f496c96ef8?q=80&w=696&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"]
  },

  {
    "id": 40,
    "name": "Urban Minimal Top",
    "category": "Women Tops",
    "brand": "MinimalMuse",
    "price": 699,
    "discountPrice": 559,
    "sizes": ["S", "M", "L"],
    "colors": ["Black"],
    "material": "Cotton",
    "fit": "Regular Fit",
    "description": "Minimalist urban casual top.",
    "images": ["https://images.unsplash.com/photo-1643825664857-7e6e4124f289?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"]
  },

  {
    "id": 41,
    "name": "Classic Comfort Tee",
    "category": "Women Tops",
    "brand": "ComfyLine",
    "price": 499,
    "discountPrice": 389,
    "sizes": ["S", "M", "L"],
    "colors": ["Grey"],
    "material": "Cotton",
    "fit": "Regular Fit",
    "description": "Comfort-first classic tee.",
    "images": ["https://images.unsplash.com/photo-1652689223597-8cecc8cc3968?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"]
  },

 {
    "id": 42,
    "name": "Modern Casual Top",
    "category": "Women Tops",
    "brand": "ModernHer",
    "price": 799,
    "discountPrice": 639,
    "sizes": ["M", "L"],
    "colors": ["Blue"],
    "material": "Cotton",
    "fit": "Regular Fit",
    "description": "Modern casual everyday top.",
    "images": ["https://plus.unsplash.com/premium_photo-1692574098105-8c38fc1f3e3c?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"]
  },

  {
    "id": 43,
    "name": "Soft Touch Cotton Tee",
    "category": "Women Tops",
    "brand": "SoftFeel",
    "price": 549,
    "discountPrice": 429,
    "sizes": ["S", "M", "L", "XL"],
    "colors": ["White"],
    "material": "Soft Cotton",
    "fit": "Regular Fit",
    "description": "Ultra-soft cotton tee.",
    "images": ["https://images.unsplash.com/photo-1767785829300-28722d89e696?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"]
  },

  {
    "id": 44,
    "name": "Relaxed Weekend Top",
    "category": "Women Tops",
    "brand": "WeekendMood",
    "price": 649,
    "discountPrice": 519,
    "sizes": ["M", "L"],
    "colors": ["Beige"],
    "material": "Cotton",
    "fit": "Relaxed Fit",
    "description": "Weekend-ready relaxed top.",
    "images": ["https://plus.unsplash.com/premium_photo-1675107359683-6d9b90aa593b?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"]
  },

  {
    "id": 45,
    "name": "Everyday Essential Tee",
    "category": "Women Tops",
    "brand": "EssentialWear",
    "price": 399,
    "discountPrice": 299,
    "sizes": ["S", "M", "L", "XL"],
    "colors": ["White"],
    "material": "Cotton",
    "fit": "Regular Fit",
    "description": "Essential cotton everyday tee.",
    "images": ["https://plus.unsplash.com/premium_photo-1683143039712-5c58e04983d9?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"]
  },

  {
    "id": 46,
    "name": "Urban Boxy Casual Top",
    "category": "Women Tops",
    "brand": "UrbanEase",
    "price": 899,
    "discountPrice": 729,
    "sizes": ["M", "L"],
    "colors": ["Black"],
    "material": "Cotton",
    "fit": "Boxy Fit",
    "description": "Urban boxy casual top.",
    "images": ["https://plus.unsplash.com/premium_photo-1680111700115-a6dc169546df?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"]
  },

  {
    "id": 47,
    "name": "Soft Cotton Relax Tee",
    "category": "Women Tops",
    "brand": "Relaxia",
    "price": 549,
    "discountPrice": 429,
    "sizes": ["S", "M", "L"],
    "colors": ["Blue"],
    "material": "Cotton",
    "fit": "Relaxed Fit",
    "description": "Soft cotton relaxed tee.",
    "images": ["https://images.unsplash.com/photo-1694955437705-07a5cb686c0a?q=80&w=690&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"]
  },

  {
    "id": 48,
    "name": "Classic Slim Cotton Top",
    "category": "Women Tops",
    "brand": "SlimHer",
    "price": 699,
    "discountPrice": 559,
    "sizes": ["S", "M", "L"],
    "colors": ["Black"],
    "material": "Cotton",
    "fit": "Slim Fit",
    "description": "Slim fit classic cotton top.",
    "images": ["https://plus.unsplash.com/premium_photo-1687188207071-f6ceb66d51e7?q=80&w=695&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"]
  },

  {
    "id": 49,
    "name": "Minimal Everyday Tee",
    "category": "Women Tops",
    "brand": "BareBasics",
    "price": 449,
    "discountPrice": 349,
    "sizes": ["S", "M", "L", "XL"],
    "colors": ["White"],
    "material": "Cotton",
    "fit": "Regular Fit",
    "description": "Minimal everyday essential tee.",
    "images": ["https://plus.unsplash.com/premium_photo-1689371957762-b5f8d601933e?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"]
  },

  {
    "id": 50,
    "name": "Premium Lounge Cotton Top",
    "category": "Women Tops",
    "brand": "LuxeEase",
    "price": 1199,
    "discountPrice": 999,
    "sizes": ["M", "L"],
    "colors": ["Cream"],
    "material": "Premium Cotton",
    "fit": "Relaxed Fit",
    "description": "Premium lounge cotton top.",
    "images": ["https://plus.unsplash.com/premium_photo-1691622500807-6d9eeb9ea06a?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"]
  },

  


]